# Generated by Django 3.1.7 on 2021-08-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Scheduling',
            },
        ),
    ]
